[package]
name = "rustboy"
version = "0.1.0"
authors = ["Charlie Boggus <charlie.boggus@gmail.com>"]
edition = "2018"

[dependencies]
glium = "0.25.0"
alto = "3.0.4"

[lib]
name = "rustboy"
path = "src/lib.rs"
edition = "2018"